# OpenCV functions for manipulating images

- Image I/O operations
- Image Properties 
- Creating new images, accessing pixels and region of interest

### Import libraries

In [1]:
# import libraries
import cv2
import numpy as np
from dataPath import DATA_PATH
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
mpl.rcParams['figure.figsize'] = (6.0, 6.0)
mpl.rcParams['image.cmap'] = 'gray'

### Reading an Image

OpenCV allows reading different types of images (JPG, PNG, etc). You can load grayscale images colour images or you can also load images with Alpha channel. It uses the imread function which has the following code syntax arguments:

Reading function code Syntax arguments:

cv2.imread(    filename[, flags]    )

It has 2 arguments:

- Path of the image file: This can be an absolute or relative path. 
- Flags (optional): These flags are used to read an image in a particular format. The default is 1. 

Flag types:

- cv2.IMREAD_GRAYSCALE or 0: Loads image in grayscale mode
- cv2.IMREAD_COLOR or 1: Loads a color image. Any transparency of image will be neglected. It is the default flag.
- cv2.IMREAD_UNCHANGED or -1: Loads image as such including alpha channel.

In [3]:
image_path = DATA_PATH + "/images/number_zero.jpg"

# Read image in Grayscale format, cv2.IMREAD_GRAYSCALE or 0:
sample_image = cv2.imread(image_path,0)
print(sample_image)

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]


### Intensity 

The values printed above are the intensity values of each pixel.

0 means black pixel and as the value increases, it moves towards white. A value of 255 is a white pixel.

### Image Properties

In [4]:
print("Data type = {}\n".format(sample_image.dtype))
print("Object type = {}\n".format(type(sample_image)))
print("Dimension of the image = {}\n".format(sample_image.shape))

Data type = uint8

Object type = <class 'numpy.ndarray'>

Dimension of the image = (13, 11)



- From the above output, we can see that the datatype is an unsigned int of 8 bit
- The image is 2D numpy array with values from 0 - 255
- The image resolution is 13 x 11 (height x width) or 13 rows and 11 columns

Also, in OpenCV, size is a tuple of width x height (columns, rows). In numpy, the shape method returns size as a tuple of height x width

### Manipulating Pixels¶

### Accessing Pixels

In the sample image, we saw that the first pixel has a value of 1. Let us check it.

Since this is a numpy array, we have zero-based indexing and we can access the first element using the index (0,0).

In [5]:
print(sample_image[0, 0])

1
